### ISSUE TITLE
Not able to run the docker image of PyLucene

### ISSUE THREAD

**Issue by prabhupant** [coady/docker#16]
I pulled the latest docker image of PyLucene and but when I tried to run, nothing happens and it does not run. It goes to exited state immediately and there are no logs as to why this is happening.

This is the docker image I am using - https://hub.docker.com/layers/coady/pylucene/latest/images/sha256-8bc358950c5a72258ef487e8769ef69429d4322006214f4d21eb9bec128ee336?context=explore

Can someone help?

**Comment by coady** [comment]
Would need more information, like the exact command.

One thing to try is this [example from the docs](https://docs.docker.com/engine/reference/commandline/run/#name), and trying another image like `python` for comparison.

**Comment by prabhupant** [comment]
@coady I pulled the latest image and ran it using docker desktop for Mac M1. Also tried it via command line. These are the commands I used

```bash
docker pull coady/pylucene:latest
docker run coady/pylucene
```

**Comment by coady** [comment]
Typically `run` is given a command or used interactively. Here are 2 examples to compare:
```
docker run python python --version
docker run -it python
```
